### ISSUE TITLE
signup: validate phone number

### ISSUE THREAD

**Issue by adamdecaf** [moov-io/auth#28]
**What were you trying to do?**

I performed a signup with an invalid email address `{..., "phone": "1", ... }` and successfully signed up. Such invalid data shouldn't be accepted. 

**What did you expect to see?**

An error message about the invalid format (or skip storing it?)

**Comment by adamdecaf** [comment]
Right now we just store it as a string in the db. https://github.com/moov-io/auth/blob/v0.2.0/signup.go#L94

We should validate any E.164 number, there might be a port of the google libphonenumber (java).

https://github.com/search?o=desc&q=language%3Ago+phone+number&s=stars&type=Repositories

**Comment by u5surf** [comment]
Hi, E.164 which you are supposed to use is required the Country code.
https://en.m.wikipedia.org/wiki/E.164 
Signup strict do not have country code.
it cannot choice validation rules.
